package GUIS.forogui;

import db.access.DBConnection;
import foro.Foro;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */

public class Frame_Foro extends javax.swing.JFrame {
    
    
    private int index = 0;
    private boolean refrescado = false;
    private DBConnection db;
    private List <String> Lista_ID;
    private List<String> Peliculas,Series;
    private String usuario;
    private boolean volver = false;
    
    private void crearTabs(List<String> disc,JPanel p,JTabbedPane pane)
    {
        int n = disc.size();
        rellenar(n,p,disc);
        n-=10;
        int i = 2;
        while(n>0)
        {
            JPanel aux = new JPanel();
            pane.add(aux,Integer.toString(i));
            rellenar(n,aux,disc);
            n-=10;
            i++;
        }
        index = 0;
    }
    private void rellenar(int n,JPanel p,List<String> disc)
    {
        Lista_ID = db.getTopicsID(1);
        p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));
        for(int i = 0;i<Math.min(n, 10);i++)
        {
        int aux = Integer.parseInt(Lista_ID.get(index));
        p.add(new DiscusionButton(disc.get(i),this,db,usuario,aux));
        index++;
        }
    }
    /**
     * Creates new form GUIS.forogui.Frame_Foro
     */
    public boolean get_volver()
    {
        return volver;
    }
    public void setVolver(boolean b)
    {
        volver = b;
    }
    public Frame_Foro(DBConnection connect,String usuario) {
        volver = false;
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        db = connect;
        this.usuario = usuario;
        //Crea el foro sin spoilers
        Peliculas = db.getTopics(1);
     
        Lista_ID = db.getTopicsID(1);
        crearTabs(Peliculas,jPanel4,jTabbedPane1);
        switchPanels(jScrollPane2);
        
       
    }
    public String getUsuario()
    {
        return usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        RefButton = new javax.swing.JButton();
        DisButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foro");
        setName("Foro"); // NOI18N
        setResizable(false);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(400, 400));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jButton1.setText("Foro películas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(172, 172, 172))
        );

        jLayeredPane1.add(jPanel2, "card4");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(94, 99, 182));
        jPanel3.setPreferredSize(new java.awt.Dimension(375, 600));

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORO DE PELÍCULAS");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(711, 375));

        jPanel4.setPreferredSize(new java.awt.Dimension(706, 375));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("1", jPanel4);

        RefButton.setText("Refrescar");
        RefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefButtonActionPerformed(evt);
            }
        });

        DisButton.setText("Iniciar discusión");
        DisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(72, 72, 72)
                        .addComponent(RefButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DisButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(RefButton)
                    .addComponent(DisButton))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("1");

        jScrollPane2.setViewportView(jPanel3);

        jLayeredPane1.add(jScrollPane2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switchPanels(jScrollPane2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVolver(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void RefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefButtonActionPerformed
        // TODO add your handling code here:
        
          
        refreshPeliculas();
       
    }//GEN-LAST:event_RefButtonActionPerformed

    private void refreshPeliculas()
    {
         jTabbedPane1.removeAll();
         jPanel4.removeAll();
         jTabbedPane1.add(jPanel4,"1");
         Peliculas = db.getTopics(1);
         crearTabs(Peliculas,jPanel4,jTabbedPane1);
    }
    private void DisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButtonActionPerformed
        // TODO add your handling code here:
        CrearDisc j = new CrearDisc(this,true);
        
        j.setResizable(false);
        j.setLocationRelativeTo(null);
        j.setFocusable(true);
        j.requestFocus();
        j.setVisible(true);
        
        //Anadir discusion a la base de datos
        if(j.getAdd())
        {
            db.createTopic(j.getNombre(), getUsuario(), 1);
            refreshPeliculas();
            //poner boolean a false ya no tenemos que anadir nada más
            j.setAdd(false);
        }
       
    }//GEN-LAST:event_DisButtonActionPerformed

                                    

    /**
     * @param args the command line arguments
     */

    public void switchPanels(Component o)
    {
       jLayeredPane1.removeAll();
       jLayeredPane1.add(o);
       jLayeredPane1.repaint();
       jLayeredPane1.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisButton;
    private javax.swing.JButton RefButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
